import { z } from "zod";

/** A full ai_faqs row for the admin list. search_vector is generated by Postgres — never read or written here. */
export const faqRowSchema = z.object({
  id: z.string(),
  question: z.string(),
  answer: z.string(),
  keywords: z.array(z.string()),
  sort_order: z.number(),
  is_active: z.boolean(),
});
export type FaqRow = z.infer<typeof faqRowSchema>;

/** The form's own state — plain strings/boolean tied to controlled inputs, same split as every other admin form in this panel. */
export type FaqFormState = {
  question: string;
  answer: string;
  keywordsText: string;
  isActive: boolean;
};

export const defaultFaqFormState: FaqFormState = {
  question: "",
  answer: "",
  keywordsText: "",
  isActive: true,
};

const rawFaqFormShape = z.object({
  question: z.string(),
  answer: z.string(),
  keywordsText: z.string(),
  isActive: z.boolean(),
});

export const faqFormSchema = rawFaqFormShape.superRefine((values, ctx) => {
  if (!values.question.trim()) {
    ctx.addIssue({ code: "custom", path: ["question"], message: "Enter the question." });
  }
  if (!values.answer.trim()) {
    ctx.addIssue({ code: "custom", path: ["answer"], message: "Enter the answer." });
  }
});

export type FaqFormErrors = Partial<Record<keyof FaqFormState, string>>;

export function validateFaqForm(values: FaqFormState): FaqFormErrors {
  const result = faqFormSchema.safeParse(values);
  if (result.success) return {};

  const errors: FaqFormErrors = {};
  for (const issue of result.error.issues) {
    const key = issue.path[0] as keyof FaqFormState | undefined;
    if (key && !errors[key]) {
      errors[key] = issue.message;
    }
  }
  return errors;
}

export type FaqWriteFields = {
  question: string;
  answer: string;
  keywords: string[];
  is_active: boolean;
};

/** Only call after validateFaqForm() returns no errors. */
export function coerceFaqFields(values: FaqFormState): FaqWriteFields {
  return {
    question: values.question.trim(),
    answer: values.answer.trim(),
    keywords: values.keywordsText
      .split(",")
      .map((word) => word.trim())
      .filter(Boolean),
    is_active: values.isActive,
  };
}
